// Action Types

// Example
// export const ACTION_TYPE = 'ACTION_TYPE'
// Action Types

export const SET_LINKED_PROFILE_DATA = "SET_LINKED_PROFILE_DATA";
export const RESET_LINKED_PROFILE_DATA = "RESET_LINKED_PROFILE_DATA";
export const UPDATE_LINKED_PROFILE_DATA = "UPDATE_LINKED_PROFILE_DATA";
export const UPDATE_EXPERIENCE_DATA = "UPDATE_EXPERIENCE_DATA";
export const UPDATE_CERTIFICATIONS_DATA = "UPDATE_CERTIFICATIONS_DATA";
export const UPDATE_PROJECTS_DATA = "UPDATE_PROJECTS_DATA";
export const SET_SKILL_DATA = "SET_SKILL_DATA";
export const UPDATE_EDUCATION_DATA = "UPDATE_EDUCATION_DATA";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const SET_TOASTER = "SET_TOASTER";
export const UPDATE_ROUTES = "UPDATE_ROUTES";
