name: CI
on: [push]
jobs:
  standard-checks:
    name: Linting and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          registry-url: "https://npm.pkg.github.com"
          scope: "@teamgeeksolution"

      - name: Clean install dependencies
        run: rm -rf node_modules && yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Run ESlint
        run: yarn lint

      # - name: Run Tests
      #   run: yarn test

      - name: Build & Bundle
        run: yarn build
